### ISSUE TITLE
Error during compilation for "Lilygo Watch 2020 v3"

### ISSUE THREAD

**Issue by Fabryz** [linuxthor/My-TTGO-Watch#7]
Hi, I'm on Platform.io under Win10, I'm trying to compile the project for my "Lilygo Watch 2020 v3", but I get these errors.
What should I do?

```
...
Compiling .pio\build\t-watch2020-v3\libc8e\SPIFFS\SPIFFS.cpp.o
Archiving .pio\build\t-watch2020-v3\lib476\libTicker.a
Indexing .pio\build\t-watch2020-v3\lib476\libTicker.a
C:\Users\Fabryz\.platformio\packages\framework-arduinoespressif32\libraries\SD\src\SD.cpp: In member function 'uint64_t fs::SDFS::totalBytes()':
C:\Users\Fabryz\.platformio\packages\framework-arduinoespressif32\libraries\SD\src\SD.cpp:85:19: error: 'struct FATFS' has no member named 'ssize'
         *(fsinfo->ssize);
                   ^
C:\Users\Fabryz\.platformio\packages\framework-arduinoespressif32\libraries\SD\src\SD.cpp: In member function 'uint64_t fs::SDFS::usedBytes()':
C:\Users\Fabryz\.platformio\packages\framework-arduinoespressif32\libraries\SD\src\SD.cpp:99:19: error: 'struct FATFS' has no member named 'ssize'
         *(fsinfo->ssize);
                   ^
Compiling .pio\build\t-watch2020-v3\lib7ac\TTGO TWatch Library\BBQ10Keyboard.cpp.o
*** [.pio\build\t-watch2020-v3\lib3c7\SD\SD.cpp.o] Error 1
============================================================================ [FAILED] Took 228.83 seconds ============================================================================
Environment     Status    Duration
--------------  --------  ------------
t-watch2020-v3  FAILED    00:03:48.830
======================================================================= 1 failed, 0 succeeded in 00:03:48.830 ======================================================================= 

```

**Comment by linuxthor** [comment]
I have access to V3 hardware so will take a look. I have restarted development with the [pwrmgm-tests](https://github.com/linuxthor/Hackers-TTGO-Watch/tree/pwrmgm-tests) branch which has various fixes. Does that also give an issue? I will try on V3 and report back in the next couple of days.

**Comment by ProposeleSS** [comment]
The issue persists when trying to build from the mentioned branch too. 

It looks like SD library is only used in some gui sources for V3

**Comment by linuxthor** [comment]
Have you tried to remove .pio and rebuild? I forgot to try V3 yet as I have been wrestling with a wifi issue but will try in a couple of hours.

**Comment by ProposeleSS** [comment]
There were 2 libraries missing (esp32-ble-keyboard and esp32-a2dp) which I added to platformio.ini

After adding those libraries, I've tried to build project and got the same error as before. Then I deleted all .pio folder, tried building and nothing changed.

I am using Ubuntu if it changes anything

**Comment by linuxthor** [comment]
Understood. I have pushed a new update to the branch. It contains various WIP stuff but also seems to fix the build. 

Could you try and let me know if it works for you please?

**Comment by ProposeleSS** [comment]
I've pulled last changes (last commit shows date of today) and the issue persists. 
The hash of latest comit: 71371f2cc9554548376c674445d2770cd7880220

**Comment by ProposeleSS** [comment]
I've experimented a little and found a workaround for this issue: I've reverted @linuxthor arduino repo to https://github.com/sharandac/arduino-esp32-hedge and I could build project successfully. I see that there is only one change between these two, but it is way over my head to fix (or understand) this. Maybe @linuxthor you will find this helpful
